updated for Zewo 0.14.0
antonmes/LibXML2 pull request #11
Opened 2016-10-05 06:25 UTC by vovasty

2016-10-17 00:25 UTC, Danappelxx requested changes
Great! Just a couple things and we're good to go 👍

2016-10-17 00:25 UTC, Danappelxx commented on Package.swift
> +        .Package(url: "https://github.com/open-swift/C7.git", majorVersion: 0, minor: 12),
We don't use C7 anymore, you can cut this dependency.

2016-10-17 00:25 UTC, Danappelxx commented on Sources/XML/XMLNode.swift
> +
cut whitespace

2016-10-17 01:30 UTC, vovasty commented
done

2016-10-18 04:32 UTC, Danappelxx commented on Package.swift
> +        .Package(url: "https://github.com/open-swift/C7.git", majorVersion: 0, minor: 12),
still there :/

2016-10-18 04:43 UTC, Danappelxx commented
CI is failing cause of some imports. Fix that and this is good to go!

2016-10-18 04:43 UTC, Danappelxx approved these changes

2016-10-18 23:17 UTC, vovasty commented
tests will fail cause needs test data files in Tests/XMLTests/TestData

2016-10-18 23:37 UTC, Danappelxx commented
Thats very strange, but you're right. Reverting my commit & merging.

2016-10-18 23:39 UTC, merged